module: KituraCompression
author: IBM
github_url: https://github.com/IBM-Swift/Kitura-Compression/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, KituraCompression.xcodeproj, -target, KituraCompression, -toolchain, org.swift.3020160823a, LIBRARY_SEARCH_PATHS=.build/debug]
